server:
  port: 8090



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yun6?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.hr.user.pojo